### ISSUE TITLE
No Internet after Configuration

### ISSUE THREAD

**Issue by droidforever** [bneijt/mullvad-edgerouter-x#1] opened 2020-05-04 21:02 UTC
I installed the wireguard/vyatta addon for er-x v2
I then went to Mullvad.net and generated a new config file
Then used this configuration.  I did not use your IP's or fake Keys
configure
edit firewall name wgIn
set description 'established only'
set default-action drop
set rule 10 action accept
set rule 10 state established enable
set rule 10 state related enable
exit
edit firewall name wgLocal
set description 'established only'
set default-action drop
set rule 10 action accept
set rule 10 state established enable
set rule 10 state related enable
exit
edit firewall ipv6-name wgIn6
set description 'established only'
set default-action drop
set rule 10 action accept
set rule 10 state established enable
set rule 10 state related enable
exit
edit firewall ipv6-name wgLocal6
set description 'established only'
set default-action drop
set rule 10 action accept
set rule 10 state established enable
set rule 10 state related enable
exit
edit interfaces wireguard wg0
set description mullvadvpn
set address {Mullvad Provided IP}/32
set address fc00:bbbb:bbbb:bb01::2:78a2/128
set listen-port 51820
set route-allowed-ips false
set peer {Public Key Mullvad} endpoint {Mullvad IP}:51820
set peer {Public Key Mullvad} allowed-ips 0.0.0.0/0
set peer {Public Key Mullvad} allowed-ips ::0/0
set private-key {Private Key Mullvad}
set fwmark 190
set firewall in name wgIn
set firewall in ipv6-name wgIn6
set firewall local name wgLocal
set firewall local ipv6-name wgLocal6
exit
edit protocols static table 190
set description 'mullvad'
set interface-route 0.0.0.0/0 next-hop-interface wg0
exit
edit service nat rule 5190
set description 'masq mullvad'
set outbound-interface wg0
set type masquerade
exit
edit firewall modify lanInModify rule 187
set description 'do not mod wireguard ever'
set action accept
set destination port 51820
set protocol udp
exit
edit firewall modify lanInModify rule 188
set description 'allow access to ISP modem'
set action accept
set destination group address-group NETv4_eth0
exit
edit firewall modify lanInModify rule 189
set description 'do not mod local targets'
set action accept
set destination group address-group NETv4_switch0
exit
edit firewall modify lanInModify rule 190
set action modify
set modify table 190
exit
set interfaces switch switch0 firewall in modify lanInModify
edit firewall name wanLocal rule 190
set action accept
set description 'accept wireguard'
set destination port 51820
set protocol udp
exit
edit firewall ipv6-name wanLocal6 rule 190
set action accept
set description 'accept wireguard'
set destination port 51820
set protocol udp
exit
edit protocols static interface-route 1.1.1.1/32
set next-hop-interface wg0
exit
commit ; save
then:
sudo ip6tables --table nat --append POSTROUTING --out-interface wg0 -j MASQUERADE

Is my problem that I used a real config?  Or is there some other error.  I can log into the router and ping the internet but my computers get no internet access.

**Comment by bneijt** [comment] 2020-05-07 12:09
Not being able to connect to the internet from your computer may indicate a few different things. Please check:
- Is your computer using the edgerouter as a gateway? (`ip route` might help)
- Forwarding between the interfaces might not be allowed yet?

**Comment by droidforever** [comment] 2020-05-10 22:18
I tried to run the script you provided on my pc and got this error:
vad-nl2.conf
  File "merc.py", line 112
    def main() -> int:
               ^
SyntaxError: invalid syntax
Then I tried running as root same problem then tried python3 and it threw several errors.  So on goes my plight.  Thank you so much for your assistance with these issues.

**Comment by bneijt** [comment] 2020-05-11 06:24
The first error you posted was because of python 2. I've updated the README to reflect that you need at least python 3.
Could you post the python 3 errors?

**Comment by droidforever** [comment] 2020-05-11 07:58
Here is the error from Python3:
Reading from: mullvad-nl2.conf
Traceback (most recent call last):
  File "merc.py", line 139, in <module>
    sys.exit(main())
  File "merc.py", line 120, in main
    interface_address0=mullvad_config["Interface"]["Address"].split(",")[0],
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'Interface'

I replaced the example.mullvad.conf with the info I received from Mullvad.  Did I make an error in doing so?

**Comment by bneijt** [comment] 2020-05-13 12:54
This seems to suggest that mullvad-nl2.conf does not have an "Interface" section or does not contain any valid configuration. Does the file mullvad-nl2.conf look ok if you open it up in a text editor?

**Comment by droidforever** [comment] 2020-05-14 04:22
haven't tried to run it yet but I got the proper config.txt.  Thank you so much for your assistance.  I am truly grateful for your guidance.

**Comment by droidforever** [comment] 2020-05-14 08:14
I ran your script. followed the promtps provided.  I can ping the mullvad provide IP.  But my internet is still going through my own ISP.
here is my config
firewall {
    all-ping enable
    broadcast-ping disable
    ipv6-name WANv6_IN {
        default-action drop
        description "WAN inbound traffic forwarded to LAN"
        enable-default-log
        rule 10 {
            action accept
            description "Allow established/related sessions"
            state {
                established enable
                related enable
            }
        }
        rule 20 {
            action drop
            description "Drop invalid state"
            state {
                invalid enable
            }
        }
    }
    ipv6-name WANv6_LOCAL {
        default-action drop
        description "WAN inbound traffic to the router"
        enable-default-log
        rule 10 {
            action accept
            description "Allow established/related sessions"
            state {
                established enable
                related enable
            }
        }
        rule 20 {
            action drop
            description "Drop invalid state"
            state {
                invalid enable
            }
        }
        rule 30 {
            action accept
            description "Allow IPv6 icmp"
            protocol ipv6-icmp
        }
        rule 40 {
            action accept
            description "allow dhcpv6"
            destination {
                port 546
            }
            protocol udp
            source {
                port 547
            }
        }
    }
    ipv6-name wanLocal6 {
        default-action drop
        rule 190 {
            action accept
            description "accept wireguard input"
            destination {
                port 51820
            }
            protocol udp
        }
    }
    ipv6-name wgIn6 {
        default-action drop
        description "established only"
        rule 10 {
            action accept
            state {
                established enable
                related enable
            }
        }
    }
    ipv6-name wgLocal6 {
        default-action drop
        description "established only"
        rule 10 {
            action accept
            state {
                established enable
                related enable
            }
        }
    }
    ipv6-receive-redirects disable
    ipv6-src-route disable
    ip-src-route disable
    log-martians enable
    modify lanInModify {
        rule 187 {
            action accept
            description "do not mod wireguard ever"
            destination {
                port 51820
            }
            protocol udp
        }
        rule 188 {
            action accept
            description "accept wireguard input"
            destination {
                group {
                    address-group NETv4_eth0
                }
                port 51820
            }
            protocol udp
        }
    }
    name WAN_IN {
        default-action drop
        description "WAN to internal"
        rule 10 {
            action accept
            description "Allow established/related"
            state {
                established enable
                related enable
            }
        }
        rule 20 {
            action drop
            description "Drop invalid state"
            state {
                invalid enable
            }
        }
    }
    name WAN_LOCAL {
        default-action drop
        description "WAN to router"
        rule 10 {
            action accept
            description "Allow established/related"
            state {
                established enable
                related enable
            }
        }
        rule 20 {
            action drop
            description "Drop invalid state"
            state {
                invalid enable
            }
        }
    }
    name wgIn {
        default-action drop
        description "established only"
        rule 10 {
            action accept
            state {
                established enable
                related enable
            }
        }
    }
    name wgLocal {
        default-action drop
        description "established only"
        rule 10 {
            action accept
            state {
                established enable
                related enable
            }
        }
    }
    receive-redirects disable
    send-redirects enable
    source-validation disable
    syn-cookies enable
}
interfaces {
    ethernet eth0 {
        address dhcp
        description Internet
        duplex auto
        firewall {
            in {
                ipv6-name WANv6_IN
                name WAN_IN
            }
            local {
                ipv6-name WANv6_LOCAL
                name WAN_LOCAL
            }
        }
        speed auto
    }
    ethernet eth1 {
        description Local
        duplex auto
        speed auto
    }
    ethernet eth2 {
        description Local
        duplex auto
        speed auto
    }
    ethernet eth3 {
        description Local
        duplex auto
        speed auto
    }
    ethernet eth4 {
        description Local
        duplex auto
        poe {
            output off
        }
        speed auto
    }
    loopback lo {
    }
    switch switch0 {
        address 192.168.1.1/24
        description Local
        mtu 1500
        switch-port {
            interface eth1 {
            }
            interface eth2 {
            }
            interface eth3 {
            }
            interface eth4 {
            }
            vlan-aware disable
        }
    }
    wireguard wg0 {
        address 10.65.147.128/32
        address fc00:bbbb:bbbb:bb01::2:937f/128
        description mullvad-nl2.conf
        firewall {
            in {
                ipv6-name wgIn6
                name wgIn
            }
            local {
                ipv6-name wgLocal6
                name wgLocal
            }
        }
        fwmark 190
        listen-port 51820
        mtu 1420
        peer EkuvafXclRe5hBEkj/smAJTcPzukj2SOYnWhpw3FPE0= {
            allowed-ips 0.0.0.0/0
            allowed-ips ::0/0
            endpoint mullvad provided server IP:51820
        }
        private-key F1SP0h/9cGaCMsOgsva27DVgIjmf7xz91rZbPnj320g=
        route-allowed-ips false
    }
}
protocols {
    static {
        interface-route 1.1.1.1/32 {
            next-hop-interface wg0 {
            }
        }
        table 190 {
            description mullvad
            interface-route 0.0.0.0/0 {
                next-hop-interface wg0 {
                }
            }
        }
    }
}
service {
    dhcp-server {
        disabled false
        hostfile-update disable
        shared-network-name LAN {
            authoritative enable
            subnet 192.168.1.0/24 {
                default-router 192.168.1.1
                dns-server 192.168.1.1
                lease 86400
                start 192.168.1.38 {
                    stop 192.168.1.243
                }
            }
        }
        static-arp disable
        use-dnsmasq disable
    }
    dns {
        forwarding {
            cache-size 150
            listen-on switch0
        }
    }
    gui {
        http-port 80
        https-port 443
        older-ciphers enable
    }
    nat {
        rule 5010 {
            description "masquerade for WAN"
            outbound-interface eth0
            type masquerade
        }
        rule 5190 {
            description "masq mullvad"
            outbound-interface wg0
            type masquerade
        }
    }
    ssh {
        port 22
        protocol-version v2
    }
}
system {
    host-name ubnt
    login {
        user admin {
            authentication {
                encrypted-password $5$8YRWijFybZJS5rvo$qxB.Ed9nDJughvT6M5jJEVCWb0CAxSjgyEZq93TanSC
            }
            level admin
        }
    }
    ntp {
        server 0.ubnt.pool.ntp.org {
        }
        server 1.ubnt.pool.ntp.org {
        }
        server 2.ubnt.pool.ntp.org {
        }
        server 3.ubnt.pool.ntp.org {
        }
    }
    syslog {
        global {
            facility all {
                level notice
            }
            facility protocols {
                level debug
            }
        }
    }
    time-zone UTC
}

**Comment by droidforever** [comment] 2020-05-17 13:27
okay I got this to work but my speed dropped from 450Mb/s down to 28.14Mb/s.  Is this what I should expect?  Or have I once again done something wrong?  Thank you in advance for your reply and all the help you've given me.

**Comment by bneijt** [comment] 2020-05-22 06:15
Wow, that is a big speed drop indeed.

I have no idea what might be causing that. I did not see a speed drop in my connection of 80Mb/s, but I also don't see any reason for the drop.

One thing that might be an issue is the router from your internet service provider. They sometimes (mine did) have priority rules set in place that they use to make sure that TCP connections get the maximum speed, while UDP connections are somewhat dropped. They then also add an exception for DNS requests to make sure that does not get pushed.

To verify this, simply change the mullvad endpoint port to 53 (the dns port) in the wireguard interface configuration. so

  set peer {public key} endpoint {mullvad ip}:51820

should become

  set peer {public key} endpoint {mullvad ip}:53

See if that helps, if so, this might be caused by ISP priority rules you may or may not be able to control.

**Comment by bneijt** [comment] 2020-05-23 18:29
If you still have issues with speed, you should consider opening an issue with the wireguard software for the ubiquity router as they might have extra information on how you might improve that speed.

I'm closing this issue as the original problem of having no internet has been solved.

Best of luck!

**Closed as completed by bneijt** 2020-05-23 18:29 UTC
Labels: question
